/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: opentelemetry/proto/collector/trace/v1/trace_service.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "opentelemetry/proto/collector/trace/v1/trace_service.pb-c.h"
void   opentelemetry__proto__collector__trace__v1__export_trace_service_request__init
                     (Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceRequest         *message)
{
  static const Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceRequest init_value = OPENTELEMETRY__PROTO__COLLECTOR__TRACE__V1__EXPORT_TRACE_SERVICE_REQUEST__INIT;
  *message = init_value;
}
size_t opentelemetry__proto__collector__trace__v1__export_trace_service_request__get_packed_size
                     (const Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceRequest *message)
{
  assert(message->base.descriptor == &opentelemetry__proto__collector__trace__v1__export_trace_service_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t opentelemetry__proto__collector__trace__v1__export_trace_service_request__pack
                     (const Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &opentelemetry__proto__collector__trace__v1__export_trace_service_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t opentelemetry__proto__collector__trace__v1__export_trace_service_request__pack_to_buffer
                     (const Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &opentelemetry__proto__collector__trace__v1__export_trace_service_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceRequest *
       opentelemetry__proto__collector__trace__v1__export_trace_service_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceRequest *)
     protobuf_c_message_unpack (&opentelemetry__proto__collector__trace__v1__export_trace_service_request__descriptor,
                                allocator, len, data);
}
void   opentelemetry__proto__collector__trace__v1__export_trace_service_request__free_unpacked
                     (Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &opentelemetry__proto__collector__trace__v1__export_trace_service_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   opentelemetry__proto__collector__trace__v1__export_trace_service_response__init
                     (Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceResponse         *message)
{
  static const Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceResponse init_value = OPENTELEMETRY__PROTO__COLLECTOR__TRACE__V1__EXPORT_TRACE_SERVICE_RESPONSE__INIT;
  *message = init_value;
}
size_t opentelemetry__proto__collector__trace__v1__export_trace_service_response__get_packed_size
                     (const Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceResponse *message)
{
  assert(message->base.descriptor == &opentelemetry__proto__collector__trace__v1__export_trace_service_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t opentelemetry__proto__collector__trace__v1__export_trace_service_response__pack
                     (const Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &opentelemetry__proto__collector__trace__v1__export_trace_service_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t opentelemetry__proto__collector__trace__v1__export_trace_service_response__pack_to_buffer
                     (const Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &opentelemetry__proto__collector__trace__v1__export_trace_service_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceResponse *
       opentelemetry__proto__collector__trace__v1__export_trace_service_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceResponse *)
     protobuf_c_message_unpack (&opentelemetry__proto__collector__trace__v1__export_trace_service_response__descriptor,
                                allocator, len, data);
}
void   opentelemetry__proto__collector__trace__v1__export_trace_service_response__free_unpacked
                     (Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &opentelemetry__proto__collector__trace__v1__export_trace_service_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   opentelemetry__proto__collector__trace__v1__export_trace_partial_success__init
                     (Opentelemetry__Proto__Collector__Trace__V1__ExportTracePartialSuccess         *message)
{
  static const Opentelemetry__Proto__Collector__Trace__V1__ExportTracePartialSuccess init_value = OPENTELEMETRY__PROTO__COLLECTOR__TRACE__V1__EXPORT_TRACE_PARTIAL_SUCCESS__INIT;
  *message = init_value;
}
size_t opentelemetry__proto__collector__trace__v1__export_trace_partial_success__get_packed_size
                     (const Opentelemetry__Proto__Collector__Trace__V1__ExportTracePartialSuccess *message)
{
  assert(message->base.descriptor == &opentelemetry__proto__collector__trace__v1__export_trace_partial_success__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t opentelemetry__proto__collector__trace__v1__export_trace_partial_success__pack
                     (const Opentelemetry__Proto__Collector__Trace__V1__ExportTracePartialSuccess *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &opentelemetry__proto__collector__trace__v1__export_trace_partial_success__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t opentelemetry__proto__collector__trace__v1__export_trace_partial_success__pack_to_buffer
                     (const Opentelemetry__Proto__Collector__Trace__V1__ExportTracePartialSuccess *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &opentelemetry__proto__collector__trace__v1__export_trace_partial_success__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Opentelemetry__Proto__Collector__Trace__V1__ExportTracePartialSuccess *
       opentelemetry__proto__collector__trace__v1__export_trace_partial_success__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Opentelemetry__Proto__Collector__Trace__V1__ExportTracePartialSuccess *)
     protobuf_c_message_unpack (&opentelemetry__proto__collector__trace__v1__export_trace_partial_success__descriptor,
                                allocator, len, data);
}
void   opentelemetry__proto__collector__trace__v1__export_trace_partial_success__free_unpacked
                     (Opentelemetry__Proto__Collector__Trace__V1__ExportTracePartialSuccess *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &opentelemetry__proto__collector__trace__v1__export_trace_partial_success__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor opentelemetry__proto__collector__trace__v1__export_trace_service_request__field_descriptors[1] =
{
  {
    "resource_spans",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceRequest, n_resource_spans),
    offsetof(Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceRequest, resource_spans),
    &opentelemetry__proto__trace__v1__resource_spans__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned opentelemetry__proto__collector__trace__v1__export_trace_service_request__field_indices_by_name[] = {
  0,   /* field[0] = resource_spans */
};
static const ProtobufCIntRange opentelemetry__proto__collector__trace__v1__export_trace_service_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor opentelemetry__proto__collector__trace__v1__export_trace_service_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest",
  "ExportTraceServiceRequest",
  "Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceRequest",
  "opentelemetry.proto.collector.trace.v1",
  sizeof(Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceRequest),
  1,
  opentelemetry__proto__collector__trace__v1__export_trace_service_request__field_descriptors,
  opentelemetry__proto__collector__trace__v1__export_trace_service_request__field_indices_by_name,
  1,  opentelemetry__proto__collector__trace__v1__export_trace_service_request__number_ranges,
  (ProtobufCMessageInit) opentelemetry__proto__collector__trace__v1__export_trace_service_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor opentelemetry__proto__collector__trace__v1__export_trace_service_response__field_descriptors[1] =
{
  {
    "partial_success",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceResponse, partial_success),
    &opentelemetry__proto__collector__trace__v1__export_trace_partial_success__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned opentelemetry__proto__collector__trace__v1__export_trace_service_response__field_indices_by_name[] = {
  0,   /* field[0] = partial_success */
};
static const ProtobufCIntRange opentelemetry__proto__collector__trace__v1__export_trace_service_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor opentelemetry__proto__collector__trace__v1__export_trace_service_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse",
  "ExportTraceServiceResponse",
  "Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceResponse",
  "opentelemetry.proto.collector.trace.v1",
  sizeof(Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceResponse),
  1,
  opentelemetry__proto__collector__trace__v1__export_trace_service_response__field_descriptors,
  opentelemetry__proto__collector__trace__v1__export_trace_service_response__field_indices_by_name,
  1,  opentelemetry__proto__collector__trace__v1__export_trace_service_response__number_ranges,
  (ProtobufCMessageInit) opentelemetry__proto__collector__trace__v1__export_trace_service_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor opentelemetry__proto__collector__trace__v1__export_trace_partial_success__field_descriptors[2] =
{
  {
    "rejected_spans",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Opentelemetry__Proto__Collector__Trace__V1__ExportTracePartialSuccess, rejected_spans),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error_message",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Opentelemetry__Proto__Collector__Trace__V1__ExportTracePartialSuccess, error_message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned opentelemetry__proto__collector__trace__v1__export_trace_partial_success__field_indices_by_name[] = {
  1,   /* field[1] = error_message */
  0,   /* field[0] = rejected_spans */
};
static const ProtobufCIntRange opentelemetry__proto__collector__trace__v1__export_trace_partial_success__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor opentelemetry__proto__collector__trace__v1__export_trace_partial_success__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "opentelemetry.proto.collector.trace.v1.ExportTracePartialSuccess",
  "ExportTracePartialSuccess",
  "Opentelemetry__Proto__Collector__Trace__V1__ExportTracePartialSuccess",
  "opentelemetry.proto.collector.trace.v1",
  sizeof(Opentelemetry__Proto__Collector__Trace__V1__ExportTracePartialSuccess),
  2,
  opentelemetry__proto__collector__trace__v1__export_trace_partial_success__field_descriptors,
  opentelemetry__proto__collector__trace__v1__export_trace_partial_success__field_indices_by_name,
  1,  opentelemetry__proto__collector__trace__v1__export_trace_partial_success__number_ranges,
  (ProtobufCMessageInit) opentelemetry__proto__collector__trace__v1__export_trace_partial_success__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor opentelemetry__proto__collector__trace__v1__trace_service__method_descriptors[1] =
{
  { "Export", &opentelemetry__proto__collector__trace__v1__export_trace_service_request__descriptor, &opentelemetry__proto__collector__trace__v1__export_trace_service_response__descriptor },
};
const unsigned opentelemetry__proto__collector__trace__v1__trace_service__method_indices_by_name[] = {
  0         /* Export */
};
const ProtobufCServiceDescriptor opentelemetry__proto__collector__trace__v1__trace_service__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "opentelemetry.proto.collector.trace.v1.TraceService",
  "TraceService",
  "Opentelemetry__Proto__Collector__Trace__V1__TraceService",
  "opentelemetry.proto.collector.trace.v1",
  1,
  opentelemetry__proto__collector__trace__v1__trace_service__method_descriptors,
  opentelemetry__proto__collector__trace__v1__trace_service__method_indices_by_name
};
void opentelemetry__proto__collector__trace__v1__trace_service__export(ProtobufCService *service,
                                                                       const Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceRequest *input,
                                                                       Opentelemetry__Proto__Collector__Trace__V1__ExportTraceServiceResponse_Closure closure,
                                                                       void *closure_data)
{
  assert(service->descriptor == &opentelemetry__proto__collector__trace__v1__trace_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void opentelemetry__proto__collector__trace__v1__trace_service__init (Opentelemetry__Proto__Collector__Trace__V1__TraceService_Service *service,
                                                                      Opentelemetry__Proto__Collector__Trace__V1__TraceService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &opentelemetry__proto__collector__trace__v1__trace_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
