FROM ubuntu:18.04
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -qq update && \
    apt-get install -y -qq curl ca-certificates build-essential libsystemd-dev \
    cmake make bash sudo wget unzip nano vim valgrind dh-make flex bison \
    libpq-dev postgresql-server-dev-all && \
    apt-get install -y -qq --reinstall lsb-base lsb-release
