include:
  - local: '/.gitlab/ci-templates.yml'

stages:
  - build
  - docker-build

"gcc DFLB_JEMALLOC=On":
  stage: build
  image: gcc
  variables:
      FLB_OPT: "-DFLB_JEMALLOC=On"
  extends: .gcc-template
  script:
    - sh ci/do-ut
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - ./build

"gcc DFLB_JEMALLOC=Off":
  stage: build
  image: gcc
  variables:
      FLB_OPT: "-DFLB_JEMALLOC=Off"
  extends: .gcc-template
  script:
    - sh ci/do-ut
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - ./build

"gcc DSANITIZE_ADDRESS=On":
  stage: build
  image: gcc
  variables:
      FLB_OPT: "-DSANITIZE_ADDRESS=On"
  extends: .gcc-template
  script:
    - sh ci/do-ut
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - ./build

"gcc DSANITIZE_UNDEFINED=On":
  stage: build
  image: gcc
  variables:
      FLB_OPT: "-DSANITIZE_UNDEFINED=On"
  extends: .gcc-template
  script:
    - sh ci/do-ut
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - ./build

"gcc DFLB_COVERAGE=On":
  stage: build
  image: gcc
  variables:
      FLB_OPT: "-DFLB_COVERAGE=On"
  extends: .gcc-template
  script:
    - sh ci/do-ut
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - ./build
      
docker-build:
  stage: docker-build
  image: docker:stable
  variables: 
    DOCKER_BUILD: 1
  services:
    - docker:dind
  before_script:
    - docker info
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - ./build
  script:
    - echo "===== BUILD DOCKER IMAGE ======="
    - docker build -t test-image -f ./build/Dockerfile .
