set (CMAKE_SYSTEM_NAME Linux )

set (CMAKE_FIND_ROOT_PATH /path/to/root )

set (CMAKE_C_COMPILER   ${CMAKE_FIND_ROOT_PATH}/path/to/c_compiler )
set (CMAKE_CXX_COMPILER ${CMAKE_FIND_ROOT_PATH}/path/to/cxx_compiler )
#set (CMAKE_INCLUDE_PATH ${CMAKE_FIND_ROOT_PATH}/include )
#set (CMAKE_LIBRARY_PATH ${CMAKE_FIND_ROOT_PATH}/lib )

set (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
