ARG inotify_mode=inotify_on

FROM debian:stretch as builder
COPY --from=amd64/busybox:1.31.0 /bin/busybox /bin/busybox
RUN chmod 555 /bin/busybox \
 && /bin/busybox --install


FROM fluent/fluent-bit:1.3 AS inotify_on

FROM fluent/fluent-bit-inotify-disabled:1.3 AS inotify_off

FROM $inotify_mode
COPY --from=builder /bin/ /bin/

