#
# Copyright (c) 2021, RT-Thread Development Team
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#

from building import *

cwd     = GetCurrentDir()

src = Split('''
libc_emcc_wrapper.c
''')

CPPPATH = [cwd]

group = DefineGroup('iwasm_libc_emcc', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
