#
# Copyright (c) 2021, RT-Thread Development Team
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#

from building import *

cwd     = GetCurrentDir()

src = Split('''
thread_manager.c
''')

CPPPATH = [cwd]

group = DefineGroup('iwasm_lib_thread_mgr', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
