# Copyright (C) 2019 Intel Corporation.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

FROM ubuntu:20.04 AS base

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    cmake build-essential git

WORKDIR /home/wamr

COPY . .

WORKDIR /home/wamr/core/iwasm/libraries/wasi-nn/test/build

RUN cmake \
  -DWAMR_BUILD_WASI_NN=1 \
  ..

RUN make -j $(grep -c ^processor /proc/cpuinfo)

FROM ubuntu:22.04

COPY --from=base /home/wamr/core/iwasm/libraries/wasi-nn/test/build/iwasm /run/iwasm

ENTRYPOINT [ "/run/iwasm" ]
