apiVersion: v1
kind: Service
metadata:
  name: logging-fluentbit-sidecar
  labels:
    app: logging-fluentbit-sidecar
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: website
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-fluentbit-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: aspnet-web
        image: mcr.microsoft.com/dotnet/framework/samples:aspnetapp
        volumeMounts:
        - mountPath: c:\inetpub\logs\LogFiles\W3SVC1\
          name: log-volume
      - name: fluentbit-logger
        image: fluent/fluent-bit:1.3.7-nanoserver
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: c:\config
          name: config          
        - mountPath: c:\logs
          name: log-volume
        - mountPath: c:\state
          name: log-state
      volumes:
      - name: config
        configMap:
          name: fluentbit-config
      - name: log-volume
        emptyDir: {}
      - name: log-state
        emptyDir: {}
      nodeSelector:
        beta.kubernetes.io/os: windows