/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: opentelemetry/proto/collector/logs/v1/logs_service.proto */

#ifndef PROTOBUF_C_opentelemetry_2fproto_2fcollector_2flogs_2fv1_2flogs_5fservice_2eproto__INCLUDED
#define PROTOBUF_C_opentelemetry_2fproto_2fcollector_2flogs_2fv1_2flogs_5fservice_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "opentelemetry_logs.pb-c.h"

typedef struct Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceRequest Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceRequest;
typedef struct Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceResponse Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceResponse;


/* --- enums --- */


/* --- messages --- */

struct  Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceRequest
{
  ProtobufCMessage base;
  /*
   * An array of ResourceLogs.
   * For data coming from a single resource this array will typically contain one
   * element. Intermediary nodes (such as OpenTelemetry Collector) that receive
   * data from multiple origins typically batch the data before forwarding further and
   * in that case this array will contain multiple elements.
   */
  size_t n_resource_logs;
  Opentelemetry__Proto__Logs__V1__ResourceLogs **resource_logs;
};
#define OPENTELEMETRY__PROTO__COLLECTOR__LOGS__V1__EXPORT_LOGS_SERVICE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&opentelemetry__proto__collector__logs__v1__export_logs_service_request__descriptor) \
    , 0,NULL }


struct  Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceResponse
{
  ProtobufCMessage base;
};
#define OPENTELEMETRY__PROTO__COLLECTOR__LOGS__V1__EXPORT_LOGS_SERVICE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&opentelemetry__proto__collector__logs__v1__export_logs_service_response__descriptor) \
     }


/* Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceRequest methods */
void   opentelemetry__proto__collector__logs__v1__export_logs_service_request__init
                     (Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceRequest         *message);
size_t opentelemetry__proto__collector__logs__v1__export_logs_service_request__get_packed_size
                     (const Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceRequest   *message);
size_t opentelemetry__proto__collector__logs__v1__export_logs_service_request__pack
                     (const Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceRequest   *message,
                      uint8_t             *out);
size_t opentelemetry__proto__collector__logs__v1__export_logs_service_request__pack_to_buffer
                     (const Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceRequest   *message,
                      ProtobufCBuffer     *buffer);
Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceRequest *
       opentelemetry__proto__collector__logs__v1__export_logs_service_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   opentelemetry__proto__collector__logs__v1__export_logs_service_request__free_unpacked
                     (Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceRequest *message,
                      ProtobufCAllocator *allocator);
/* Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceResponse methods */
void   opentelemetry__proto__collector__logs__v1__export_logs_service_response__init
                     (Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceResponse         *message);
size_t opentelemetry__proto__collector__logs__v1__export_logs_service_response__get_packed_size
                     (const Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceResponse   *message);
size_t opentelemetry__proto__collector__logs__v1__export_logs_service_response__pack
                     (const Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceResponse   *message,
                      uint8_t             *out);
size_t opentelemetry__proto__collector__logs__v1__export_logs_service_response__pack_to_buffer
                     (const Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceResponse   *message,
                      ProtobufCBuffer     *buffer);
Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceResponse *
       opentelemetry__proto__collector__logs__v1__export_logs_service_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   opentelemetry__proto__collector__logs__v1__export_logs_service_response__free_unpacked
                     (Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceRequest_Closure)
                 (const Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceRequest *message,
                  void *closure_data);
typedef void (*Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceResponse_Closure)
                 (const Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct Opentelemetry__Proto__Collector__Logs__V1__LogsService_Service Opentelemetry__Proto__Collector__Logs__V1__LogsService_Service;
struct Opentelemetry__Proto__Collector__Logs__V1__LogsService_Service
{
  ProtobufCService base;
  void (*export)(Opentelemetry__Proto__Collector__Logs__V1__LogsService_Service *service,
                 const Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceRequest *input,
                 Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceResponse_Closure closure,
                 void *closure_data);
};
typedef void (*Opentelemetry__Proto__Collector__Logs__V1__LogsService_ServiceDestroy)(Opentelemetry__Proto__Collector__Logs__V1__LogsService_Service *);
void opentelemetry__proto__collector__logs__v1__logs_service__init (Opentelemetry__Proto__Collector__Logs__V1__LogsService_Service *service,
                                                                    Opentelemetry__Proto__Collector__Logs__V1__LogsService_ServiceDestroy destroy);
#define OPENTELEMETRY__PROTO__COLLECTOR__LOGS__V1__LOGS_SERVICE__BASE_INIT \
    { &opentelemetry__proto__collector__logs__v1__logs_service__descriptor, protobuf_c_service_invoke_internal, NULL }
#define OPENTELEMETRY__PROTO__COLLECTOR__LOGS__V1__LOGS_SERVICE__INIT(function_prefix__) \
    { OPENTELEMETRY__PROTO__COLLECTOR__LOGS__V1__LOGS_SERVICE__BASE_INIT,\
      function_prefix__ ## export  }
void opentelemetry__proto__collector__logs__v1__logs_service__export(ProtobufCService *service,
                                                                     const Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceRequest *input,
                                                                     Opentelemetry__Proto__Collector__Logs__V1__ExportLogsServiceResponse_Closure closure,
                                                                     void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor opentelemetry__proto__collector__logs__v1__export_logs_service_request__descriptor;
extern const ProtobufCMessageDescriptor opentelemetry__proto__collector__logs__v1__export_logs_service_response__descriptor;
extern const ProtobufCServiceDescriptor opentelemetry__proto__collector__logs__v1__logs_service__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_opentelemetry_2fproto_2fcollector_2flogs_2fv1_2flogs_5fservice_2eproto__INCLUDED */