/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: common.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include <opentelemetry/common.pb-c.h>
#include "opentelemetry_common.pb-c.h"
void   opentelemetry__proto__common__v1__instrumentation_scope__init
                     (Opentelemetry__Proto__Common__V1__InstrumentationScope         *message)
{
  static const Opentelemetry__Proto__Common__V1__InstrumentationScope init_value = OPENTELEMETRY__PROTO__COMMON__V1__INSTRUMENTATION_SCOPE__INIT;
  *message = init_value;
}
size_t opentelemetry__proto__common__v1__instrumentation_scope__get_packed_size
                     (const Opentelemetry__Proto__Common__V1__InstrumentationScope *message)
{
  assert(message->base.descriptor == &opentelemetry__proto__common__v1__instrumentation_scope__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t opentelemetry__proto__common__v1__instrumentation_scope__pack
                     (const Opentelemetry__Proto__Common__V1__InstrumentationScope *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &opentelemetry__proto__common__v1__instrumentation_scope__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t opentelemetry__proto__common__v1__instrumentation_scope__pack_to_buffer
                     (const Opentelemetry__Proto__Common__V1__InstrumentationScope *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &opentelemetry__proto__common__v1__instrumentation_scope__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Opentelemetry__Proto__Common__V1__InstrumentationScope *
       opentelemetry__proto__common__v1__instrumentation_scope__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Opentelemetry__Proto__Common__V1__InstrumentationScope *)
     protobuf_c_message_unpack (&opentelemetry__proto__common__v1__instrumentation_scope__descriptor,
                                allocator, len, data);
}
void   opentelemetry__proto__common__v1__instrumentation_scope__free_unpacked
                     (Opentelemetry__Proto__Common__V1__InstrumentationScope *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &opentelemetry__proto__common__v1__instrumentation_scope__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}

static const ProtobufCFieldDescriptor opentelemetry__proto__common__v1__instrumentation_scope__field_descriptors[4] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Opentelemetry__Proto__Common__V1__InstrumentationScope, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "version",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Opentelemetry__Proto__Common__V1__InstrumentationScope, version),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "attributes",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Opentelemetry__Proto__Common__V1__InstrumentationScope, n_attributes),
    offsetof(Opentelemetry__Proto__Common__V1__InstrumentationScope, attributes),
    &opentelemetry__proto__common__v1__key_value__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dropped_attributes_count",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Opentelemetry__Proto__Common__V1__InstrumentationScope, dropped_attributes_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned opentelemetry__proto__common__v1__instrumentation_scope__field_indices_by_name[] = {
  2,   /* field[2] = attributes */
  3,   /* field[3] = dropped_attributes_count */
  0,   /* field[0] = name */
  1,   /* field[1] = version */
};
static const ProtobufCIntRange opentelemetry__proto__common__v1__instrumentation_scope__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor opentelemetry__proto__common__v1__instrumentation_scope__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "opentelemetry.proto.common.v1.InstrumentationScope",
  "InstrumentationScope",
  "Opentelemetry__Proto__Common__V1__InstrumentationScope",
  "opentelemetry.proto.common.v1",
  sizeof(Opentelemetry__Proto__Common__V1__InstrumentationScope),
  4,
  opentelemetry__proto__common__v1__instrumentation_scope__field_descriptors,
  opentelemetry__proto__common__v1__instrumentation_scope__field_indices_by_name,
  1,  opentelemetry__proto__common__v1__instrumentation_scope__number_ranges,
  (ProtobufCMessageInit) opentelemetry__proto__common__v1__instrumentation_scope__init,
  NULL,NULL,NULL    /* reserved[123] */
};