#!/bin/sh

### BEGIN INIT INFO
# Provides:	  fluent-bit
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the fluent-bit service
# Description:       starts fluent-bit using start-stop-daemon
### END INIT INFO

PATH=/opt/fluent-bit/bin/:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/opt/fluent-bit/bin/fluent-bit
NAME=fluent-bit
DESC=fluent-bit

start_fluent_bit() {
	# Start the daemon/service
	#
	# Returns:
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
	start-stop-daemon --start --quiet --exec $DAEMON 2>/dev/null || return 2
}

test_config() {
	# Test the fluent_bit configuration
	$DAEMON --dry-run -c /etc/fluent-bit/fluent-bit.conf
}

stop_fluent_bit() {
	# Stops the daemon/service
	#
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred
	start-stop-daemon --stop --quiet --name $NAME
}

case "$1" in
	start)
		start_fluent_bit
		;;
	stop)
		stop_fluent_bit
		;;
	restart)

		# Check configuration before stopping fluent_bit
		if ! test_config; then
			exit $?
		fi

		stop_fluent_bit
		case "$?" in
			0|1)
				start_fluent_bit
				;;
			*)
				# Failed to stop
				;;
		esac
		;;
	configtest|testconfig)
		test_config
		;;
	*)
		echo "Usage: $NAME {start|stop|restart|reload|force-reload|status|configtest}" >&2
		exit 3
		;;
esac

