[SERVICE]
    Flush           1
    Daemon          Off
    Log_Level       info
    Parsers_File    parsers.conf
    Plugins_File    plugins.conf
    HTTP_Server     Off
    HTTP_Listen     0.0.0.0
    HTTP_Port       2020
    Storage.Metrics On

[INPUT]
    Name   forward
    Listen 0.0.0.0
    Port   24224

[OUTPUT]
    Name  stdout
    Match *
