FROM opensuse/leap:latest

RUN zypper -n update && \
    zypper -n install curl ca-certificates gcc gcc-c++ systemd-devel cmake make\
    bash sudo wget unzip nano vim valgrind dh-make flex bison rpmbuild \
    postgresql postgresql-devel
