general:
  # Only unfixed should go here
  # Order by priority then year then ascending value
  vulnerabilities:
    # Critical
    - CVE-2021-33574
    - CVE-2021-35942
    # High
    - CVE-2018-12886
    - CVE-2019-3843
    - CVE-2019-3844
    - CVE-2019-12290
    - CVE-2019-15847
    - CVE-2020-1751
    - CVE-2020-1752
    - CVE-2021-3326
    - CVE-2021-33560
    - CVE-2021-43618
  bestPracticeViolations:
    # Fatal
    - DKL-DI-0005 # Clear apt-get caches
    # Warn
    - CIS-DI-0001 # Create a user for the Container
    - DKL-DI-0006 # Avoid latest tag
    # Info
    - CIS-DI-0005 # Enable content trust for Docker
    - CIS-DI-0006 # Add HEALTHCHECK instruction to the container image
    - CIS-DI-0008 # Confirm safety of setuid/setgid files
    # Skip
    - DKL-LI-0001 # Avoid empty password
