# Install script for directory: /Users/adheipsingh/parseable/fluent-bit/plugins

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Debug")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

# Set path to fallback-tool for dependency-resolution.
if(NOT DEFINED CMAKE_OBJDUMP)
  set(CMAKE_OBJDUMP "/Library/Developer/CommandLineTools/usr/bin/objdump")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/custom_calyptia/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_blob/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_node_exporter_metrics/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_kubernetes_events/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_kafka/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_fluentbit_metrics/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_prometheus_scrape/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_emitter/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_tail/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_dummy/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_head/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_health/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_http/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_collectd/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_statsd/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_opentelemetry/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_elasticsearch/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_calyptia_fleet/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_splunk/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_prometheus_remote_write/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_event_type/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_storage_backlog/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_nginx_exporter_metrics/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_stream_processor/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_serial/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_stdin/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_syslog/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_exec/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_udp/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_exec_wasi/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_tcp/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_mqtt/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_lib/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_forward/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/in_random/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/processor_content_modifier/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/processor_labels/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/processor_metrics_selector/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/processor_sql/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/processor_opentelemetry_envelope/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_azure/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_azure_blob/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_azure_logs_ingestion/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_azure_kusto/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_bigquery/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_calyptia/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_counter/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_datadog/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_es/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_exit/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_file/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_forward/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_http/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_influxdb/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_logdna/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_loki/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_kafka/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_kafka_rest/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_nats/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_nrlogs/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_null/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_opensearch/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_oracle_log_analytics/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_parseable/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_plot/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_skywalking/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_slack/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_splunk/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_stackdriver/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_stdout/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_syslog/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_tcp/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_udp/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_td/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_lib/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_flowcounter/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_gelf/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_websocket/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_cloudwatch_logs/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_kinesis_firehose/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_kinesis_streams/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_opentelemetry/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_prometheus_exporter/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_prometheus_remote_write/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_s3/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_vivo_exporter/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/out_chronicle/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_alter_size/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_aws/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_checklist/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_ecs/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_record_modifier/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_sysinfo/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_throttle/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_type_converter/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_kubernetes/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_modify/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_multiline/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_nest/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_parser/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_expect/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_grep/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_rewrite_tag/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_log_to_metrics/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_lua/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_stdout/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_geoip2/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_nightfall/cmake_install.cmake")
  include("/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/filter_wasm/cmake_install.cmake")

endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
if(CMAKE_INSTALL_LOCAL_ONLY)
  file(WRITE "/Users/adheipsingh/parseable/fluent-bit/plugins/plugins/install_local_manifest.txt"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
endif()
