#
# Copyright (c) 2021, RT-Thread Development Team
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#

from building import *

cwd     = GetCurrentDir()

src = Split('''
lib_pthread_wrapper.c
''')

CPPPATH = [cwd]


group = DefineGroup('iwasm_lib_pthread', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
