#
# Copyright (c) 2021, RT-Thread Development Team
#
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#

from building import *
import re

Import('rtconfig')

cwd     = GetCurrentDir()

src = Glob('*.c')

if rtconfig.ARCH == 'arm':
    if re.match('^cortex-m.*', rtconfig.CPU):
        src += ['arch/invokeNative_thumb.s']
    elif re.match('^cortex-a.*', rtconfig.CPU):
        src += ['arch/invokeNative_arm.s']
elif rtconfig.ARCH == 'ia32':
    src += ['arch/invokeNative_ia32.s']

CPPPATH = [cwd, cwd + '/../include']

group = DefineGroup('iwasm_common', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
