.\" libxbee - a C library to aid the use of Digi's Series 1 XBee modules
.\"           running in API mode.
.\" 
.\" Copyright (C) 2009 onwards  Attie Grande (attie@attie.co.uk)
.\" 
.\" libxbee is free software: you can redistribute it and/or modify it
.\" under the terms of the GNU Lesser General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\" 
.\" libxbee is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU Lesser General Public License for more details.
.\" 
.\" You should have received a copy of the GNU Lesser General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.TH XBEE_CONGETTYPES 3  02-Mar-2012 "GNU" "Linux Programmer's Manual"
.SH NAME
xbee_conGetTypes
.SH SYNOPSIS
.B #include <xbee.h>
.sp
.BI "xbee_err xbee_conGetTypes(struct xbee *" xbee ", char ***" retList ");"
.ad b
.SH DESCRIPTION
.sp
.BR xbee_conGetTypes ()
allows you to retrieve a list of connection types that are provided by the given libxbee instance's mode. Once you have used the returned array, you should
.BR free ()
the pointer to avoid memory leaks. The last item in the array is set to
.B NULL
to mark the end.
.sp
For a list of connection types generally avaliable, please see
.BR xbee_conNew (3).
.SS Return Value
On success this function will return XBEE_ENONE, otherwise an error number from
.IR "enum xbee_errors" " (as specified in " <xbee.h> )
.SH EXAMPLE
.in +4n
.nf
#include <xbee.h>

struct xbee *xbee;
char **types;
int i;

/* initialize xbee, using xbee_setup() */

if (xbee_conGetTypes(xbee, &types) != XBEE_ENONE) return;

for (i = 0; types[i]; i++) {
	printf("type %d: %s\\n", i, types[i]);
}

free(types);
.fi
.in
.SH AUTHOR
Attie Grande <attie@attie.co.uk> 
.SH "SEE ALSO"
.BR libxbee (3),
.BR xbee_setup (3),
.BR xbee_conNew (3)
