FROM amazonlinux:2

RUN yum -y update && \
    yum install -y rpm-build curl ca-certificates gcc gcc-c++ cmake make bash \
                   wget unzip systemd-devel wget flex bison \
                   cyrus-sasl-lib cyrus-sasl-devel openssl openss-libs openssl-devel \
                   postgresql-devel postgresql-libs \
                   cmake3 
