<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>Index of %_html_title_%</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      <h1>Index of %_html_title_%</h1>
      <div class="table-responsive">
      <table class="table table-hover table-bordered">
        <thead>
          <tr>
            <th>
              Name
            </th>
            <th>
              Last time modified
            </th>
            <th>
              Size
            </th>
          </tr>
        </thead>
        <tbody>
