# Copyright (C) 2019 Intel Corporation. All rights reserved.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# # This will generate SDK for both runtime and wasm application
config:
	./build_sdk.sh -i

menuconfig:
	./menuconfig.sh

