services:
  fluentbit:
# Comment out `image` and uncomment `build` to build the fluent-bit image from local source
    image: fluent/fluent-bit:latest
#    build:
#      context: ../../
#      dockerfile: dockerfiles/Dockerfile
    depends_on:
      loki:
        condition: service_healthy
    container_name: fluentbit
    command: /fluent-bit/bin/fluent-bit -c /etc/fluent-bit_loki_out-structured_metadata_map.yaml
    ports:
      - 2021:2021
    networks:
      - loki-network
    volumes:
      - ./config/fluent-bit_loki_out-structured_metadata_map.yaml:/etc/fluent-bit_loki_out-structured_metadata_map.yaml

  grafana:
    image: grafana/grafana:11.5.2
    attach: false
    depends_on:
      - loki
      - fluentbit
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    networks:
      - loki-network
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  loki:
    image: grafana/loki:3.4.2
    attach: false
    command: -config.file=/etc/loki/loki-config.yaml
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "/dev/null", "http://localhost:3100/ready" ]
      interval: 5s
      retries: 10
      start_period: 10s
      timeout: 10s
    networks:
      - loki-network
    ports:
      - 3100:3100
    volumes:
      - ./config/loki-config.yaml:/etc/loki/loki-config.yaml

networks:
  loki-network:
    driver: bridge
