#!/bin/sh

set -e

case "${1}" in
	configure)
		chmod +x /etc/init.d/fluent-bit
		;;

	abort-upgrade|abort-remove|abort-deconfigure)

		;;

	*)
		echo "postinst called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/fluent-bit" ]; then
		update-rc.d fluent-bit defaults >/dev/null
		if [ -n "$2" ]; then
			_dh_action=restart
		else
			_dh_action=start
		fi
		invoke-rc.d fluent-bit $_dh_action || exit 1
	fi
fi


exit 0
