#!/bin/sh

set -e

case "${1}" in
	remove)

		;;

	purge|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)

		;;

	*)
		echo "postrm called with unknown argument \`${1}'" >&2
		exit 1
		;;
esac

if [ "$1" = "purge" ] ; then
	update-rc.d fluent-bit remove >/dev/null
fi


exit 0
