#!/bin/sh
set -e
# Automatically added by dh_installinit/12.10
if [ -x "/etc/init.d/fluent-bit" ] && [ "$1" = remove ]; then
	invoke-rc.d fluent-bit stop || exit 1
fi
# End automatically added section
