#!/bin/bash

set -e

if [[ $1 == "remove" ]]; then
    systemctl stop fluent-bit.service || true
    systemctl disable fluent-bit.service || true
else
    echo "Unknown Argument! $1" || false
fi

exit 0
