SET(HOST arm-linux)

SET(CROSS_PREFIX ${HOST}-)
SET(CROSS_TOOLCHAIN_PATH /home/travis/build/fluent/fluent-bit/ksz9692/${HOST})

SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_C_COMPILER ${CROSS_PREFIX}gcc)
SET(CMAKE_CXX_COMPILER ${CROSS_PREFIX}g++)

SET(CMAKE_FIND_ROOT_PATH ${CROSS_TOOLCHAIN_PATH})
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
