# libbacktrace.cmake
# Build configuration for libbacktrace library
# Supports: Windows (MSVC), Linux, macOS, and other Unix-like systems

set(LIBBACKTRACE_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/${FLB_PATH_LIB_LIBBACKTRACE})
set(LIBBACKTRACE_FOUND FALSE)

# Try to find system libbacktrace first (if enabled)
if(FLB_PREFER_SYSTEM_LIB_BACKTRACE)
  find_path(LIBBACKTRACE_INCLUDE_DIRS NAMES backtrace.h)
  find_library(LIBBACKTRACE_LIBRARIES NAMES backtrace)

  if(LIBBACKTRACE_INCLUDE_DIRS AND LIBBACKTRACE_LIBRARIES)
    message(STATUS "libbacktrace: using system library (${LIBBACKTRACE_LIBRARIES})")
    include_directories(${LIBBACKTRACE_INCLUDE_DIRS})
    link_directories(${LIBBACKTRACE_LIBRARY_DIRS})
    set(LIBBACKTRACE_FOUND TRUE)
    FLB_DEFINITION(FLB_HAVE_LIBBACKTRACE)
  endif()
endif()

# Build libbacktrace if system library not found
if(NOT LIBBACKTRACE_FOUND)
  if(MSVC)
    # ============================================================
    # Windows/MSVC: Build directly with CMake
    # ============================================================
    # autoconf/configure doesn't work with MSVC, so we build directly
    message(STATUS "libbacktrace: building directly with CMake for Windows/MSVC")

    # Match configure.ac behavior for unwind support:
    # - GCC/clang with libunwind API -> backtrace.c
    # - MSVC cl.exe -> nounwind.c
    set(LIBBACKTRACE_BACKTRACE_SOURCE ${LIBBACKTRACE_SOURCE_DIR}/backtrace.c)
    set(LIBBACKTRACE_BACKTRACE_SUPPORTED 1)
    if(CMAKE_C_COMPILER_ID STREQUAL "MSVC")
      set(LIBBACKTRACE_BACKTRACE_SOURCE ${LIBBACKTRACE_SOURCE_DIR}/nounwind.c)
      set(LIBBACKTRACE_BACKTRACE_SUPPORTED 0)
    endif()

    # Core source files (always needed)
    set(LIBBACKTRACE_CORE_SOURCES
      ${LIBBACKTRACE_SOURCE_DIR}/atomic.c
      ${LIBBACKTRACE_SOURCE_DIR}/dwarf.c
      ${LIBBACKTRACE_SOURCE_DIR}/fileline.c
      ${LIBBACKTRACE_SOURCE_DIR}/posix.c
      ${LIBBACKTRACE_SOURCE_DIR}/print.c
      ${LIBBACKTRACE_SOURCE_DIR}/sort.c
      ${LIBBACKTRACE_SOURCE_DIR}/state.c
    )

    # Platform-specific source files for Windows
    # - Backtrace implementation: backtrace.c (uses C++ unwind API)
    # - Format: pecoff.c (for PE/COFF format on Windows)
    # - View: read.c (file reading, not mmap for Windows)
    # - Alloc: alloc.c (standard alloc, not mmap for Windows)
    set(LIBBACKTRACE_PLATFORM_SOURCES
      ${LIBBACKTRACE_BACKTRACE_SOURCE}
      ${LIBBACKTRACE_SOURCE_DIR}/pecoff.c
      ${LIBBACKTRACE_SOURCE_DIR}/read.c
      ${LIBBACKTRACE_SOURCE_DIR}/alloc.c
    )

    set(LIBBACKTRACE_SOURCES
      ${LIBBACKTRACE_CORE_SOURCES}
      ${LIBBACKTRACE_PLATFORM_SOURCES}
    )

    # Create config.h for Windows (normally generated by autoconf)
    # Place it in a subdirectory to avoid conflicts, then add to include path
    set(LIBBACKTRACE_CONFIG_DIR "${CMAKE_CURRENT_BINARY_DIR}/libbacktrace_config")
    file(MAKE_DIRECTORY ${LIBBACKTRACE_CONFIG_DIR})
    set(LIBBACKTRACE_CONFIG_H "${LIBBACKTRACE_CONFIG_DIR}/config.h")
    file(WRITE ${LIBBACKTRACE_CONFIG_H}
      "/* config.h for Windows/MSVC - generated by CMake */\n"
      "#ifndef CONFIG_H\n"
      "#define CONFIG_H\n"
      "\n"
      "/* ELF size: 32 or 64 */\n"
      "#define BACKTRACE_ELF_SIZE 0\n"
      "\n"
      "/* XCOFF size: 32 or 64 */\n"
      "#define BACKTRACE_XCOFF_SIZE 0\n"
      "\n"
      "/* Define to 1 if you have the __atomic functions (GCC/clang builtins) */\n"
      "/* MSVC doesn't support __atomic builtins, so undefine for Windows */\n"
      "#undef HAVE_ATOMIC_FUNCTIONS\n"
      "\n"
      "/* Define to 1 if you have the __sync functions (GCC/clang only) */\n"
      "#undef HAVE_SYNC_FUNCTIONS\n"
      "\n"
      "/* Define if _Unwind_GetIPInfo is available (GCC/clang unwind API) */\n"
      "#undef HAVE_GETIPINFO\n"
      "\n"
      "/* Define to 1 if you have the declaration of `_pgmptr', and to 0 if you don't. */\n"
      "#define HAVE_DECL__PGMPTR 1\n"
      "\n"
      "/* Define to 1 if you have the declaration of `strnlen', and to 0 if you don't. */\n"
      "#define HAVE_DECL_STRNLEN 1\n"
      "\n"
      "/* Define to 1 if you have the <stdint.h> header file. */\n"
      "#define HAVE_STDINT_H 1\n"
      "\n"
      "/* Define to 1 if you have the <stdlib.h> header file. */\n"
      "#define HAVE_STDLIB_H 1\n"
      "\n"
      "/* Define to 1 if you have the <string.h> header file. */\n"
      "#define HAVE_STRING_H 1\n"
      "\n"
      "/* Define to 1 if you have the <sys/stat.h> header file. */\n"
      "#define HAVE_SYS_STAT_H 1\n"
      "\n"
      "/* Define to 1 if you have the <sys/types.h> header file. */\n"
      "#define HAVE_SYS_TYPES_H 1\n"
      "\n"
      "/* Define to 1 if you have the <windows.h> header file. */\n"
      "#define HAVE_WINDOWS_H 1\n"
      "\n"
      "/* Define to 1 if you have the <tlhelp32.h> header file. */\n"
      "#define HAVE_TLHELP32_H 1\n"
      "\n"
      "/* Define to 1 if you have the ANSI C header files. */\n"
      "#define STDC_HEADERS 1\n"
      "\n"
      "/* Define to the full name of this package. */\n"
      "#define PACKAGE_NAME \"libbacktrace\"\n"
      "\n"
      "/* Define to the version of this package. */\n"
      "#define PACKAGE_VERSION \"1.0\"\n"
      "\n"
      "#endif /* CONFIG_H */\n"
    )

    # Create unistd.h compatibility wrapper for MSVC.
    # libbacktrace sources include <unistd.h> directly, but MSVC does not
    # provide that header.
    set(LIBBACKTRACE_UNISTD_H "${LIBBACKTRACE_CONFIG_DIR}/unistd.h")
    file(WRITE ${LIBBACKTRACE_UNISTD_H}
      "/* unistd.h compatibility for Windows/MSVC - generated by CMake */\n"
      "#ifndef LIBBACKTRACE_UNISTD_H\n"
      "#define LIBBACKTRACE_UNISTD_H\n"
      "\n"
      "#include <io.h>\n"
      "#include <process.h>\n"
      "#include <sys/types.h>\n"
      "\n"
      "#ifndef _SSIZE_T_DEFINED\n"
      "#ifdef _WIN64\n"
      "#include <BaseTsd.h>\n"
      "#ifdef ssize_t\n"
      "#undef ssize_t\n"
      "#endif\n"
      "typedef SSIZE_T ssize_t;\n"
      "#else\n"
      "typedef int ssize_t;\n"
      "#endif\n"
      "#define _SSIZE_T_DEFINED\n"
      "#endif\n"
      "\n"
      "#ifndef read\n"
      "#define read _read\n"
      "#endif\n"
      "\n"
      "#ifndef close\n"
      "#define close _close\n"
      "#endif\n"
      "\n"
      "#ifndef open\n"
      "#define open _open\n"
      "#endif\n"
      "\n"
      "#ifndef lseek\n"
      "#define lseek _lseeki64\n"
      "#endif\n"
      "\n"
      "#ifndef getpid\n"
      "#define getpid _getpid\n"
      "#endif\n"
      "\n"
      "#endif /* LIBBACKTRACE_UNISTD_H */\n"
    )

    # Create backtrace-supported.h for Windows (normally generated by autoconf)
    set(LIBBACKTRACE_SUPPORTED_H "${LIBBACKTRACE_CONFIG_DIR}/backtrace-supported.h")
    file(WRITE ${LIBBACKTRACE_SUPPORTED_H}
      "/* backtrace-supported.h for Windows/MSVC - generated by CMake */\n"
      "/* Copyright (C) 2012-2024 Free Software Foundation, Inc. */\n"
      "\n"
      "/* BACKTRACE_SUPPORTED will be #define'd as 1 if the backtrace library\n"
      "   should work, 0 if it will not.  Libraries may #include this to make\n"
      "   other arrangements.  */\n"
      "\n"
      "/* Stack unwind availability depends on the compiler runtime. */\n"
      "#define BACKTRACE_SUPPORTED ${LIBBACKTRACE_BACKTRACE_SUPPORTED}\n"
      "\n"
      "/* BACKTRACE_USES_MALLOC will be #define'd as 1 if the backtrace\n"
      "   library will call malloc as it works, 0 if it will call mmap\n"
      "   instead.  On Windows we use alloc.c (malloc) not mmap.c */\n"
      "#define BACKTRACE_USES_MALLOC 1\n"
      "\n"
      "/* BACKTRACE_SUPPORTS_THREADS will be #define'd as 1 if the backtrace\n"
      "   library is configured with threading support, 0 if not.  */\n"
      "/* __sync/__atomic are not available under MSVC cl.exe. */\n"
      "#define BACKTRACE_SUPPORTS_THREADS 0\n"
      "\n"
      "/* BACKTRACE_SUPPORTS_DATA will be #defined'd as 1 if the backtrace_syminfo\n"
      "   will work for variables.  It will always work for functions.  */\n"
      "/* configure.ac sets this to 'no' for PE/COFF. */\n"
      "#define BACKTRACE_SUPPORTS_DATA 0\n"
    )

    # Build libbacktrace as a static library
    add_library(libbacktrace STATIC ${LIBBACKTRACE_SOURCES})
    target_include_directories(libbacktrace PUBLIC
      ${LIBBACKTRACE_SOURCE_DIR}
      ${LIBBACKTRACE_CONFIG_DIR}
    )

    # Windows-specific compile definitions
    # These match what configure would set for Windows
    target_compile_definitions(libbacktrace PRIVATE
      HAVE_WINDOWS_H=1
      HAVE_DECL__PGMPTR=1
      HAVE_STDLIB_H=1
      HAVE_STRING_H=1
      HAVE_STDINT_H=1
      STDC_HEADERS=1
      BACKTRACE_ELF_SIZE=0
      BACKTRACE_XCOFF_SIZE=0
      PACKAGE_NAME="libbacktrace"
      PACKAGE_VERSION="1.0"
    )

    # Set output name to match expected name
    set_target_properties(libbacktrace PROPERTIES
      OUTPUT_NAME "backtrace"
    )

    set(LIBBACKTRACE_LIBRARIES "libbacktrace")
    set(LIBBACKTRACE_FOUND TRUE)
    FLB_DEFINITION(FLB_HAVE_LIBBACKTRACE)

  else()
    # ============================================================
    # Unix-like systems (Linux, macOS, BSD, etc.): Use autoconf
    # ============================================================
    message(STATUS "libbacktrace: building with autoconf/configure")

    # Handle macOS SDK path for C compiler
    if(CMAKE_OSX_SYSROOT)
      # From macOS Mojave, /usr/include does not store C SDK headers.
      # For libbacktrace building on macOS, we have to tell C headers where they are located.
      set(DEPS_C_COMPILER "${CMAKE_C_COMPILER} -isysroot ${CMAKE_OSX_SYSROOT}")
    else()
      set(DEPS_C_COMPILER "${CMAKE_C_COMPILER}")
    endif()

    # Set up build paths
    set(FLB_LIBBACKTRACE_PATH "${CMAKE_CURRENT_BINARY_DIR}/backtrace-prefix/lib/libbacktrace.a")

    # Build using ExternalProject with autoconf/configure
    ExternalProject_Add(backtrace
      SOURCE_DIR ${LIBBACKTRACE_SOURCE_DIR}
      CONFIGURE_COMMAND ${LIBBACKTRACE_SOURCE_DIR}/configure
                        ${AUTOCONF_HOST_OPT}
                        --prefix=<INSTALL_DIR>
                        --enable-shared=no
                        --enable-static=yes
      BUILD_COMMAND ${EXTERNAL_BUILD_TOOL}
      BUILD_BYPRODUCTS ${FLB_LIBBACKTRACE_PATH}
      INSTALL_COMMAND ${EXTERNAL_BUILD_TOOL} DESTDIR= install
    )

    # Create imported target for the built library
    add_library(libbacktrace STATIC IMPORTED GLOBAL)
    set_target_properties(libbacktrace PROPERTIES
      IMPORTED_LOCATION ${FLB_LIBBACKTRACE_PATH}
    )
    add_dependencies(libbacktrace backtrace)

    # Include directories
    include_directories("${CMAKE_CURRENT_BINARY_DIR}/backtrace-prefix/include/")

    set(LIBBACKTRACE_LIBRARIES "libbacktrace")
    set(LIBBACKTRACE_FOUND TRUE)
    FLB_DEFINITION(FLB_HAVE_LIBBACKTRACE)
  endif()
endif()

# Summary
if(LIBBACKTRACE_FOUND)
  message(STATUS "libbacktrace: enabled (${LIBBACKTRACE_LIBRARIES})")
else()
  message(WARNING "libbacktrace: not available - stacktrace support will be disabled")
endif()
