# List of bundled libraries
set(FLB_PATH_LIB_CO      "lib/flb_libco")
set(FLB_PATH_LIB_RBTREE  "lib/rbtree")
set(FLB_PATH_LIB_MSGPACK "lib/msgpack-3.2.0")
set(FLB_PATH_LIB_CHUNKIO "lib/chunkio")
set(FLB_PATH_LIB_LUAJIT  "lib/LuaJIT-2.1.0-beta3")
set(FLB_PATH_LIB_MONKEY  "lib/monkey")
set(FLB_PATH_LIB_JSMN    "lib/jsmn")
set(FLB_PATH_LIB_MBEDTLS "lib/mbedtls-2.16.5")
set(FLB_PATH_LIB_SQLITE  "lib/sqlite-amalgamation-3310000")
set(FLB_PATH_LIB_ONIGMO  "lib/onigmo")
set(FLB_PATH_LIB_MPACK   "lib/mpack-amalgamation-1.0")
set(FLB_PATH_LIB_MINIZ   "lib/miniz")
set(FLB_PATH_LIB_TUTF8E  "lib/tutf8e")
