# List of bundled libraries
set(FLB_PATH_LIB_CFL         "lib/cfl")
set(FLB_PATH_LIB_FLUENT_OTEL "lib/fluent-otel-proto")
set(FLB_PATH_LIB_CMETRICS    "lib/cmetrics")
set(FLB_PATH_LIB_CTRACES     "lib/ctraces")

set(FLB_PATH_LIB_CO          "lib/flb_libco")
set(FLB_PATH_LIB_RBTREE      "lib/rbtree")
set(FLB_PATH_LIB_MSGPACK     "lib/msgpack-c")
set(FLB_PATH_LIB_AVRO        "lib/avro")
set(FLB_PATH_LIB_CHUNKIO     "lib/chunkio")
set(FLB_PATH_LIB_LUAJIT      "lib/luajit-3065c9")
set(FLB_PATH_LIB_MONKEY      "lib/monkey")
set(FLB_PATH_LIB_JSMN        "lib/jsmn")
set(FLB_PATH_LIB_MBEDTLS     "lib/mbedtls-2.28.0")
set(FLB_PATH_LIB_SQLITE      "lib/sqlite-amalgamation-3390300")
set(FLB_PATH_LIB_JANSSON     "lib/jansson-e23f558")
set(FLB_PATH_LIB_ONIGMO      "lib/onigmo")
set(FLB_PATH_LIB_MPACK       "lib/mpack-amalgamation-1.1")
set(FLB_PATH_LIB_MINIZ       "lib/miniz")
set(FLB_PATH_LIB_TUTF8E      "lib/tutf8e")
set(FLB_PATH_LIB_CARES       "lib/c-ares-1.19.0")
set(FLB_PATH_LIB_SNAPPY      "lib/snappy-fef67ac")
set(FLB_PATH_LIB_RDKAFKA     "lib/librdkafka-2.1.0")
set(FLB_PATH_LIB_RING_BUFFER "lib/lwrb")
set(FLB_PATH_LIB_WASM_MICRO_RUNTIME  "lib/wasm-micro-runtime-WAMR-1.1.1")
