# List of bundled libraries
set(FLB_PATH_LIB_CO      "lib/flb_libco")
set(FLB_PATH_LIB_RBTREE  "lib/rbtree")
set(FLB_PATH_LIB_MSGPACK "lib/msgpack-c")
#add this back in on the next RP
#set(FLB_PATH_LIB_AVRO    "lib/avro")
set(FLB_PATH_LIB_CHUNKIO "lib/chunkio")
set(FLB_PATH_LIB_LUAJIT  "lib/luajit-2.1.0-dd5032e")
set(FLB_PATH_LIB_MONKEY  "lib/monkey")
set(FLB_PATH_LIB_JSMN    "lib/jsmn")
set(FLB_PATH_LIB_MBEDTLS "lib/mbedtls-2.24.0")
set(FLB_PATH_LIB_SQLITE  "lib/sqlite-amalgamation-3330000")
set(FLB_PATH_LIB_JANSSON "lib/jansson")
set(FLB_PATH_LIB_ONIGMO  "lib/onigmo")
set(FLB_PATH_LIB_MPACK   "lib/mpack-amalgamation-1.0")
set(FLB_PATH_LIB_MINIZ   "lib/miniz")
set(FLB_PATH_LIB_TUTF8E  "lib/tutf8e")
set(FLB_PATH_LIB_XXHASH  "lib/xxHash-0.8.0")
