if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(powerpc|ppc)64le")
  message(STATUS "Forcing characters to be signed, as on x86_64.")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsigned-char")
  message(STATUS "This platform does not support WAMR building so disabled.")
  set(FLB_WASM OFF)
  message(STATUS "This platform does not support LuaJIT so disabled.")
  set(FLB_LUAJIT OFF)
endif ()
