name: fluent-bit
base: core18
summary: High performance logs and stream processor
description: |
  Fluent Bit is a high performance log processor and stream processor for Linux.
  It provides a flexible pluggable architecture to collect, enrich and deliver
  logs or metrics to multiple databases or cloud providers.
license: 'Apache-2.0'
icon: ./snap/fluent-bit.svg

adopt-info: fluent-bit
confinement: 'strict'

apps:
  fluent-bit:
    command: fluent-bit -c $SNAP/etc/fluent-bit/fluent-bit.conf
    daemon: simple
    plugs: [network, network-bind]

parts:
  fluent-bit:
    source: ./
    plugin: cmake
    stage-packages:
        - libsasl2-2
        - libssl1.1
        - libpq5
    build-packages:
        - g++
        - make
        - libsasl2-dev
        - libsystemd-dev
        - flex
        - bison
        - valgrind
        - libssl-dev
        - libpq5
        - postgresql-server-dev-all
        - git
    configflags:
        - -DFLB_DEBUG=On
        - -DFLB_OUT_KAFKA=On
        - -DFLB_JEMALLOC=On
        - -DFLB_EXAMPLES=OFF
        - -DFLB_SHARED_LIB=Off
        - -DFLB_OUT_PGSQL=On
    override-pull: |
      snapcraftctl pull
      version="$(git rev-parse --abbrev-ref HEAD)"
      [ -n "$(echo $version | grep 'master')" ] && grade=devel || grade=stable
      snapcraftctl set-version "$version"
      snapcraftctl set-grade "$grade"
