name: Build containers for a specific branch of 1.9+
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of Fluent Bit to build, commit, branch, etc. The container image will be ghcr.io/fluent/fluent-bit/test/<this value>.
        required: true
        default: master
jobs:
  build-branch-containers:
    uses: ./.github/workflows/call-build-images.yaml
    with:
      version: ${{ github.event.inputs.version }}
      ref: ${{ github.event.inputs.version }}
      registry: ghcr.io
      username: ${{ github.actor }}
      image: ${{ github.repository }}/test/${{ github.event.inputs.version }}
      unstable: ${{ github.event.inputs.version }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
