on:
  push:
    branches:
      - master
  workflow_dispatch:

name: Build packages for master
jobs:
  master-build-generate-matrix:
    name: Staging build matrix
    runs-on: ubuntu-latest
    outputs:
      build-matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      # Set up the list of target to build so we can pass the JSON to the reusable job
      - id: set-matrix
        run: |
          matrix=$((
            echo '{ "distro" : [ "debian/bullseye", "ubuntu/16.04", "ubuntu/18.04", "ubuntu/20.04" ]}'
          ) | jq -c .)
          echo $matrix
          echo $matrix| jq .
          echo "::set-output name=matrix::$matrix"
        shell: bash

  master-build-packages:
    needs: master-build-generate-matrix
    uses: fluent/fluent-bit/.github/workflows/call-build-packages.yaml@master
    with:
      version: master
      branch: master
      build_matrix: ${{ needs.master-build-generate-matrix.outputs.build-matrix }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
