name: Build PR docker images for integration tests
on:
  pull_request:
    branches:
      - master
    types: [ labeled ]
jobs:
  docker_build:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'ok-to-test')
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract metadata from Github
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: fluentbitdev/fluent-bit
          tags: |
            raw,x86_64-master-pr-${{ github.event.number }}

      - name: Build the staging image
        uses: docker/build-push-action@v2
        with:
          file: ./dockerfiles/Dockerfile.x86_64-master
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          push: false
          load: true

      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: fluentbitdev/fluent-bit:x86_64-master-pr-${{ github.event.number }}