name: Run integration tests for master
on:
  workflow_run:
    workflows: [ 'Build master docker images for integration tests' ]
    types:
      - completed
jobs:
  publish-docker-images:
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        tag: [ 'master', 'master_debug' ]

    name: publish the docker images for master
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: calyptia/fluent-bit-ci
          path: ci

      - name: Download docker image from build artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: integration-build-docker-master.yaml
          run_id: ${{ github.event.workflow_run.id }}
          name: action_image_artifact_${{ env.dockerhub_organization }}_fluent-bit_${{ env.arch }}-${{ matrix.tag }}
          path: images
        env:
          arch: x86_64
          dockerhub_organization: fluentbitdev

      - name: Import docker image
        run: |
          docker load --input ./images/${{ env.dockerhub_organization }}_fluent-bit_${{ env.arch }}-${{ matrix.tag }}
        env:
          arch: x86_64
          dockerhub_organization: fluentbitdev

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to Docker Hub
        run: |
          docker push ${{ env.dockerhub_organization }}/fluent-bit:${{ env.arch }}-${{ matrix.tag }}
        env:
          arch: x86_64
          dockerhub_organization: fluentbitdev

      - run: |
          ./scripts/grafana-add-tag.sh
        if: matrix.tag == 'master'
        env:
          GRAFANA_CLOUD_TOKEN: ${{ secrets.GRAFANA_CLOUD_TOKEN }}
          COMMIT_ID: ${{ github.event.workflow_run.head_sha }}
        working-directory: ci/

  run-integration-gcp:
    name: run integration tests on GCP
    needs: publish-docker-images
    uses: calyptia/fluent-bit-ci/.github/workflows/reusable-integration-test-gcp.yaml@main
    with:
      image_name: fluentbitdev/fluent-bit
      image_tag: x86_64-master
    secrets:
      grafana_username: ${{ secrets.GRAFANA_USERNAME }}
      terraform_api_token: ${{ secrets.TF_API_TOKEN }}
      gcp_service_account_key: ${{ secrets.GCP_SA_KEY }}
      grafana_password: ${{ secrets.GRAFANA_PASSWORD }}