name: Lint PRs
on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hadolint-pr:
    runs-on: ubuntu-latest
    name: PR - Hadolint
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Run hadolint
        uses: reviewdog/action-hadolint@921946a7ebaaf08ac72607bad67209f4e52b5407 # v1.50.5
        with:
          exclude: |
            packaging/testing/smoke/packages/Dockerfile.*

  shellcheck-pr:
    runs-on: ubuntu-latest
    name: PR - Shellcheck
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Run shellcheck
        uses: reviewdog/action-shellcheck@4c07458293ac342d477251099501a718ae5ef86e # v1.32.0
        with:
          github_token: ${{ secrets.github_token }}
          fail_level: "warning"
          reporter: github-pr-review # Better annotation in PRs
          exclude: |
            */.git/*
            ./cmake/sanitizers-cmake/**
            ./lib/**
            ./plugins/**
            ./tests/**

  actionlint-pr:
    runs-on: ubuntu-latest
    name: PR - Actionlint
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Run actionlint
        uses: reviewdog/action-actionlint@6fb7acc99f4a1008869fa8a0f09cfca740837d9d # v1.72.0
        with:
          # Disable shellcheck as done elsewhere and speeds up process
          actionlint_flags: -shellcheck=
          fail_level: "warning"
          reporter: github-pr-review # Better annotation in PRs
          github_token: ${{ secrets.github_token }}
