---
name: Release sync from server to bucket

# This is only expected to be invoked on-demand.
on:
  workflow_dispatch:
    inputs:
      mode:
        description: Optionally run in various modes to exercise the download but not upload, etc.
        required: false
        default: ''

concurrency: release-sync

jobs:
  release-sync-s3:
    name: Sync to release bucket
    runs-on: ubuntu-18.04 # no createrepo on Ubuntu 20.04
    environment: release
    steps:
      - name: Checkout code for action at least
        uses: actions/checkout@v3

      - uses: ./.github/actions/release-bucket-sync
        with:
          bucket: ${{ secrets.AWS_S3_BUCKET_RELEASE }}
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          server_hostname: ${{ secrets.FLUENTBITIO_HOST }}
          server_username: ${{ secrets.FLUENTBITIO_USERNAME }}
          server_key: ${{ secrets.FLUENTBITIO_SSHKEY }}
          mode: ${{ github.event.inputs.mode }}
