---
name: Release from staging a particular version

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to release
        required: true
        default: 99.99.99

env:
  STAGING_REGISTRY: ghcr.io
  STAGING_IMAGE_NAME: ${{ github.repository }}

  # docker.io/fluent/fluent-bit
  RELEASE_REGISTRY: docker.io
  RELEASE_IMAGE_NAME: ${{ secrets.DOCKERHUB_ORGANIZATION }}

  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_STAGING }}
  # To use with Minio locally
  # AWS_S3_ENDPOINT: http://localhost:9000

jobs:
  staging-release-packages:
    runs-on: ubuntu-latest
    # Just sync everything to the release server

  staging-release-images:
    runs-on: ubuntu-latest
    # Use skopeo to do all the work
    steps:
      - name: Sync container images from staging to release
        run: |
          docker run --rm quay.io/skopeo/stable:latest \
            sync --all \
            --src-creds ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            --dest-creds ${{ secrets.DOCKERHUB_USERNAME }}:${{ secrets.DOCKERHUB_TOKEN }} \
            --src docker --dest docker \
            ${{ env.STAGING_REGISTRY }}/${{ env.STAGING_IMAGE_NAME }} \
            ${{ env.RELEASE_REGISTRY }}//${{ env.RELEASE_IMAGE_NAME }}
