---
name: Deploy multiarch containers to staging

on:
  workflow_call:
    inputs:
      version:
        description: Version to build in 1.2.3 format
        required: true
        type: string
    secrets:
      token:
        required: true

env:
  # Containers
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-staging-images-matrix:
    name: Build multi-arch container images
    runs-on: [ ubuntu-latest ]
    environment: staging
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        buildkitd-flags: --debug

    - name: Log in to the Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.token }}

    - name: Extract metadata from Github
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          raw,multiarch-${{ inputs.version }}
          raw,multiarch-latest

    - name: Build the staging image
      uses: docker/build-push-action@v2
      with:
        file: ./dockerfiles/Dockerfile.multiarch.linuxbuilder
        context: .
        tags: fb-builder:multiarch-${{ inputs.version }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64, linux/arm64, linux/arm/v7
        push: false
        load: true
        build-args: |
          FLB_TARBALL=https://github.com/fluent/fluent-bit/archive/v${{ inputs.version }}.tar.gz

    - name: Build the staging image
      uses: docker/build-push-action@v2
      with:
        file: ./dockerfiles/Dockerfile.multiarch.linuxbuilder
        context: .
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64, linux/arm64, linux/arm/v7
        push: true
        load: false
        build-args: |
          BUILDER_IMAGE=fb-builder:multiarch-${{ inputs.version }}
