---
name: Update Dockerhub description

on:
  workflow_dispatch:

jobs:
  update-dockerhub:
    name: Update Dockerhub description
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@1b9a80c056b620d92cedb9d9b5a223409c68ddfa # v5.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ github.repository }}
          readme-filepath: ./dockerfiles/dockerhub-description.md
          short-description: 'Fluent Bit, lightweight logs and metrics collector and forwarder'
