# Copyright (C) 2019 Intel Corporation.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

FROM ubuntu:20.04 AS base

ENV DEBIAN_FRONTEND=noninteractive

# hadolint ignore=DL3008
RUN apt-get update && apt-get install -y \
  cmake build-essential git --no-install-recommends

WORKDIR /home/wamr

COPY . .

WORKDIR /home/wamr/product-mini/platforms/linux/build

# hadolint ignore=DL3008
RUN apt-get install -y wget ca-certificates --no-install-recommends \
  && mkdir /usr/local/share/ca-certificates/cacert.org \
  && wget -qP /usr/local/share/ca-certificates/cacert.org http://www.cacert.org/certs/root.crt http://www.cacert.org/certs/class3.crt \
  && update-ca-certificates \
  && git config --global http.sslCAinfo /etc/ssl/certs/ca-certificates.crt

RUN cmake \
  -DWAMR_BUILD_WASI_NN=1 \
  ..

RUN make -j "$(grep -c ^processor /proc/cpuinfo)"

FROM ubuntu:22.04

COPY --from=base /home/wamr/product-mini/platforms/linux/build/iwasm /iwasm

ENTRYPOINT [ "/iwasm" ]
